---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  namespace: 009-grpc
spec:
  selector:
    service: ambassador
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
